Sprint 1
vitalymuravyev/middle.messenger.praktikum.yandex pull request #1
Opened 2022-06-26 21:13 UTC by vitalymuravyev

2022-06-27 05:22 UTC, podlovchenko requested changes
Привет) Спасибо выполненную работу, оставила несколько некритичных замечаний
Но нужно еще обновить файл readme, указать ссылку на приложение на netlify и макеты

2022-06-27 05:22 UTC, podlovchenko commented on src/components/styles/chat_preview.css
> +    border-bottom: 1px solid #EAEAEA;
Цвета лучше выносить в css переменные, чтобы потом было удобно поменять их по всему проекту

2022-06-27 05:22 UTC, podlovchenko commented on src/components/styles/chat_preview.css
> +.chat-preview__unread > span {
Лучше не использовать теги и вложенность, а сделать отдельный отдельный класс
[Статья на эту тему](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-06-27 05:22 UTC, podlovchenko commented on src/components/styles/input.css
> +    top: 5px;
Как сейчас выглядит label при вводе в инпуте
<img width="384" alt="Снимок экрана 2022-06-27 в 08 17 34" src="https://user-images.githubusercontent.com/22602747/175865252-cba7df9b-0abf-4034-b811-734a53379101.png">
Лучше label убрать с поля ввода (сдвинуть позицию), либо убрать и поставить placeholder на инпуте, которые скрывается при вводе

2022-06-27 11:39 UTC, vitalymuravyev commented on src/components/styles/input.css
> +    top: 5px;
сделал временно. откл. часть стилей, оставил себе коммент. Очень хочется стилями сделать)

2022-06-28 09:36 UTC, podlovchenko commented
Все хорошо, работу принимаю)

2022-06-28 09:49 UTC, merged