Sprint 3
vitalymuravyev/middle.messenger.praktikum.yandex pull request #3
Opened 2022-08-10 20:51 UTC by vitalymuravyev

2022-08-11 09:40 UTC, podlovchenko requested changes
Привет, не получается проверить работу системы

<img width="811" alt="Снимок экрана 2022-08-11 в 12 37 33" src="https://user-images.githubusercontent.com/22602747/184106035-fdb53c94-dd10-444e-8b11-cc67fd0034f7.png">

При обновлении страницы `Cannot GET /sign-up`

На нетлифае старая версия

2022-08-11 09:44 UTC, vitalymuravyev commented
Привет!!!
Странно, но у меня на нетлифай все норм, только что еще раз проверил. Может кеш какой-то у тебя остался?

2022-08-11 10:14 UTC, podlovchenko commented
Да, видимо кеш был
Сейчас как и локально не могу зайти в систему
<img width="687" alt="Снимок экрана 2022-08-11 в 13 13 01" src="https://user-images.githubusercontent.com/22602747/184112290-0388080a-2ff1-485a-9582-a2c15935d0ad.png">

2022-08-11 10:55 UTC, vitalymuravyev commented
Странное поведение, учитывая что ко мне ты не заходила, видимо осталась в системе с другой проверки. Локально помогает переход на .../settings и там нажать выход. На нетлифай такой трюк не работает(

2022-08-11 16:04 UTC, podlovchenko requested changes
При обновлении страницы  `Cannot GET /messenger`

Нужно поправить app.js
```
app.get('/*', (req, res) => {
  res.sendFile(path.resolve(__dirname, './index.html'));
});
```

Если пользователь в системе, то не нужно показывать форму входа, а сразу редиректить на страницу чатов

На странице редактирование профиля никак не показано, что форма не прошла валидацию

Было бы здорово постараться избавиться от типа any в проекте, его использование является не очень хорошей практикой, и настроить eslint

2022-08-11 16:04 UTC, podlovchenko commented on package.json
> +    "chai": "^4.3.6",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-11 16:04 UTC, podlovchenko commented on src/components/Message/message.hbs
> +</div>
В проекте в некоторых файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-08-11 16:04 UTC, podlovchenko commented on src/core/Block.ts
>  export default class Block {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-08-11 16:04 UTC, podlovchenko commented on src/core/Block.ts
> +  // eslint-disable-next-line @typescript-eslint/no-empty-function
eslint стоит настроить так чтобы не приходилось выключать проверки

2022-08-11 16:04 UTC, podlovchenko commented on src/core/Block.ts
> +    // this.getContent().style.display = 'none';
Закомментированный код не стоит оставлять в проекте

2022-08-11 16:04 UTC, podlovchenko commented on src/core/api/authAPI.ts
> +    return this.fetch.post('/auth/logout', {});
Можно сделать options не обязательным параметром, чтобы не приходилось передавать пустой объект

2022-08-11 16:04 UTC, podlovchenko commented on src/core/fetch.ts
> +  get = (url: string, options: IOptions): Promise<XMLHttpRequest> => {
Было бы здорово иметь возможно указывать тип для возвращаемого значения извне
```suggestion
 get = <T>(url: string, options: IOptions): Promise<T> => {
```

2022-08-11 16:04 UTC, podlovchenko commented on src/core/fetch.ts
> +  headers?: any;
Record<string, string>

2022-08-11 16:04 UTC, podlovchenko commented on src/core/fetch.ts
> +enum METHODS {
Обычно enum именуется в формате PascalCase

2022-08-12 15:38 UTC, podlovchenko requested changes

2022-08-12 15:38 UTC, podlovchenko commented on app.js
>    res.sendFile(path.resolve(__dirname, './index.html'));
Неправильно указан путь
Нужно
`path.join(__dirname, 'dist')`

2022-08-12 15:38 UTC, podlovchenko commented on src/core/router/Route.ts
> +  _block: Block<any> | null;
Можно сделать класс Route и функцию renderDom также дженериками

2022-08-13 09:00 UTC, podlovchenko requested changes
Проверь, пожалуйста, работу приложения, прежде чем сдавать)
Если все ок, то после этой правки работу приму

2022-08-13 09:00 UTC, podlovchenko commented on app.js
> +  res.sendFile(path.resolve(__dirname, 'dist'));
res.sendFile(path.resolve(path.join(__dirname, 'dist'), './index.html'));

2022-08-13 09:56 UTC, vitalymuravyev commented on app.js
> +  res.sendFile(path.resolve(__dirname, 'dist'));
я сначала не понял, про что ты, вроде все работало. А потом как понял))) Спасибо

2022-08-13 12:54 UTC, podlovchenko commented
Принята)

2022-08-13 13:12 UTC, merged